[asdf]
    packages = [
        "aws-iam-authenticator",
        "direnv",
        "gcloud",
        "kops",
        "kubectl",
        "kubectx",
        "python",
        "terraform",
    ]

[asdf.bin]
