[linux]
    packages = [
        "p7zip",
        "bat",
        "du-dust",
        "git",
        "git-delta",
        "eza",
        "fd",
        "fzf",
        "jaq",
        "kalc",
        "ripgrep",
        "starship",
        "tealdeer",
        "unzip",
        "vivid",
        "yazi",
        "zoxide",
        "zsh",
    ]
    work = [
        "asdf",
        "direnv",
        "helm",
        "helmfile",
        "kubectx",
    ]

[linux.bin]
    p7zip = "7z"
    du-dust = "dust"
    git-delta = "delta"
    paper-terminal = "paper"
    ripgrep = "rg"
    tealdeer = "tldr"
