[msys2.packages]
    common = [
        "pactoys",
        "openssh",
        "unzip",
        "zsh",
    ]
    # noteworthy cli editors: micro helix
    prefixed = [
        "7zip",
        "bat",
        "ca-certificates",
        "delta",
        "eza",
        "fd",
        "fzf",
        "gdu",
        "jq",
        "python-tldr",
        "ripgrep",
        "starship",
        "vivid",
        "zoxide",
    ]
