[msys2.packages]
    main = [
        "nano-syntax-highlighting",
        "pactoys",
        "openssh",
        "unzip",
        "zsh",
    ]
    # noteworthy cli editors: micro helix
    msystem = [
        "7zip",
        "bat",
        "delta",
        "dust",
        "eza",
        "fd",
        "fzf",
        "jq",
        "ripgrep",
        "rust",
        "starship",
        "vivid",
        "yazi",
        "zoxide",
    ]

[msys2.bin]
    7zip = "7z"
    diffutils = "diff"
    openssh = "ssh"
    pactoys = "pacboy"
    paper-terminal = "paper"
    python-tldr = "tldr"
    ripgrep = "rg"
