[rust]
    packages = [
        "bat",
        "du-dust",
        "git-delta",
        "eza",
        "fd",
        "mdcat",
        "ripgrep",
        "starship",
        "tealdeer",
        "viu",
        "vivid",
        "yazi",
        "zoxide",
    ]

[rust.bin]
    du-dust = "dust"
    git-delta = "delta"
    paper-terminal = "paper"
    ripgrep = "rg"
    tealdeer = "tldr"

[rust.features]
