[[windows.copyfiles]]
    # Run Windows Terminal in Quake Mode on startup
    ifExists = "$Env:USERPROFILE/scoop/shims/WindowsTerminal.exe"
    src = "$Env:CHEZMOI_SOURCE_DIR/.internals/Windows/Startup/Quake Terminal.lnk"
    dst = "$Env:USERPROFILE/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Quake Terminal.lnk"

[[windows.copyfiles]]
    # Run pageant on startup
    ifExists = "$Env:USERPROFILE/scoop/shims/pageant.exe"
    src = "$Env:CHEZMOI_SOURCE_DIR/.internals/Windows/Startup/pageant.lnk"
    dst = "$Env:USERPROFILE/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/pageant.lnk"
